### ISSUE TITLE
Heartbeat bug

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/localcast#12]
Uncaught node.js Error 

Error: missed heartbeat
    at deadline [as _onTimeout](/Users/therold/Programming/Javascript/localcast/node_modules/nodecastor/lib/channel.js:68:16)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

Something in the Nodecastor lib is not right.

**Comment by normanrz** [comment]
Actually I don't think it's a nodecastor bug. It's expected behavior.

Missing a heartbeat usually means the device is disconnected/off or there are network hiccups. Maybe you should just log these errors and ignore. Or do more sophisticated logic like waiting for 5 missed heartbeats and disconnect then.
